Repository DeepDive-Final-Project/frontend, pull requests merged in 2025-04, with the labels that each got.

#100 [feat] 채팅 유저 프로필 데이터 연동 및 버튼 상태 분기 처리
  src/App.tsx
  src/components/chatting/ChatProfileInfo.tsx
  src/components/common/ProfileCard.tsx
  src/pages/ProfilePreviewPage.tsx
  src/types/userProfileType.ts
Labels: feat

#107 [fix] 채팅 관련 페이지 자잘한 스타일 및 버그 수정
  src/components/chatting/ChatMessageItem.tsx
  src/components/common/ConfirmModal.tsx
  src/pages/ChatPage.tsx
  src/pages/ProfilePreviewPage.tsx
Labels: bug, design, fix

#126 [feat] 채팅 메시지 입력 시 자동으로 하단 스크롤 이동 기능 구현
  src/components/chatting/ChatRoom.tsx
  src/components/chatting/ChatSideBar.tsx
Labels: feat

#141 [feat] 채팅방 리스트 안 읽은 메시지 수 인디케이터 표시 테스트
  src/components/chatting/ChatListItem.tsx
  src/components/chatting/ChatRoom.tsx
  src/pages/ProfilePreviewPage.tsx
Labels: feat

#143 [feat] 공통 헤더 컴포넌트 구현
  src/components/common/ChatProfile.tsx
  src/components/layout/headers/CommonNav.tsx
  src/pages/profile/LoginPage.tsx
Labels: design, feat

#152 [feat] 채팅 실시간 메시지 알림, 안읽은 표시, 읽음 처리 기능 구현
  src/App.tsx
  src/components/chatting/ChatListItem.tsx
  src/components/chatting/ChatRoom.tsx
  src/pages/ChatPage.tsx
  src/stores/useChatListStore.ts
  src/stores/useSocketStore.ts
Labels: feat

#163 [refactor] 채팅 기능에서 nickname 참조를 clientId로 일괄 수정
  package.json
  src/hooks/useChatRequest.ts
  src/hooks/useChatRequestFetch.ts
  src/pages/ChatPage.tsx
  src/pages/ProfilePreviewPage.tsx
  src/pages/TestPage.tsx
  src/services/chatListApi.ts
  src/services/chatRequestListApi.ts
Labels: refactor

#165 fix: 채팅 기능에서 clientId 참조 오류 수정
  src/components/chatting/ChatInput.tsx
  src/components/chatting/ChatRoom.tsx
  src/types/chatMessageType.ts
Labels: fix

#168 [fix] 읽음 처리 기능 오류
  src/pages/ChatPage.tsx
Labels: bug, fix

#172 [fix] 읽음 처리 기능 오류
  src/components/chatting/ChatInput.tsx
  src/components/chatting/ChatRoom.tsx
  src/stores/useChatListStore.ts
Labels: bug, fix

#173 [fix] 읽음 처리 오류 수정
  src/pages/ChatPage.tsx
  src/types/chatRoomType.ts
Labels: bug, fix
