Repository DeepDive-Final-Project/frontend, pull requests merged in 2025-03, with the labels that each got.

#7 [design] 채팅 화면 UI 구현
  .gitignore
  eslint.config.js
  package.json
  pnpm-lock.yaml
  public/.gitkeep
  public/font/Pretendard-Black.woff2
  public/font/Pretendard-Bold.woff2
  public/font/Pretendard-ExtraBold.woff2
  public/font/Pretendard-ExtraLight.woff2
  public/font/Pretendard-Light.woff2
  public/font/Pretendard-Medium.woff2
  public/font/Pretendard-Regular.woff2
  public/font/Pretendard-SemiBold.woff2
  public/font/Pretendard-Thin.woff2
  src/App.tsx
  src/assets/images/explore.svg
  src/components/Chat/ChatFilter.tsx
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatInput.tsx
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatListItem.tsx
  src/components/Chat/ChatProfileInfo.tsx
  src/components/Chat/ChatRequestCard.tsx
  src/components/Chat/ChatRequestMessage.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/Chat/ChatSideBar.tsx
  src/components/common/Button.tsx
  src/components/common/buttonVariants.ts
  src/index.css
  src/pages/Chat.tsx
  src/styles/font.css
  src/types/chatRoom.ts
  src/utils/formatTime.ts
  tailwind.config.js
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: design

#11 [design] 위도 경도 페이지 UI 구현
  package-lock.json
  package.json
  src/App.tsx
  src/assets/현이 (1).jpg
  src/components/Location/BottomSheet.tsx
  src/components/Location/Filter.tsx
  src/components/Location/InterestSelector.tsx
  src/components/Location/Tag.tsx
  src/components/Location/UserCard.tsx
  src/components/Location/UserList.tsx
  src/components/Location/UserLocation.tsx
  src/pages/Location.tsx
  src/stores/useUserStore.ts
Labels: design

#12 [design] 프로필 기본 정보 등록 UI 구현
  src/App.tsx
  src/components/profile/InputField.tsx
  src/components/profile/InputFieldLabel.tsx
  src/pages/profile/ProfileImgPage.tsx
  src/pages/profile/ProfileInfoPage.tsx
Labels: design

#19 [feat] 채팅 요청 및 수락/거절에 따른 채팅방 생성 기능 구현
  .gitignore
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/.gitkeep
  src/components/.gitkeep
  src/components/Chat/ChatHeader.tsx
  src/components/Chat/ChatList.tsx
  src/components/Chat/ChatListItem.tsx
  src/components/Chat/ChatRequestCard.tsx
  src/components/Chat/ChatRequestMessage.tsx
  src/components/Chat/ChatRoom.tsx
  src/components/common/.gitkeep
  src/components/common/Button.tsx
  src/components/common/buttonVariants.ts
  src/hooks/useAcceptRequest.ts
  src/hooks/useChatReceivedList.ts
  src/hooks/useChatRequest.ts
  src/hooks/useChatSentList.ts
  src/hooks/useRejectRequest.ts
  src/main.tsx
  src/pages/.gitkeep
  src/pages/Chat.tsx
  src/pages/ChatPage.tsx
  src/pages/TestPage.tsx
  src/stores/.gitkeep
  src/types/.gitkeep
  src/types/chatRequestType.ts
  src/types/chatRoomType.ts
  src/utils/.gitkeep
  src/utils/api.ts
  src/utils/chat/chatRoomId.ts
  src/utils/chat/formatTime.ts
  src/vite-env.d.ts
Labels: feat

#21 [feat] 로그인 페이지 구현
  src/App.tsx
  src/assets/images/github.svg
  src/assets/images/google.svg
  src/assets/images/kakao.svg
  src/components/profile/LoginButton.tsx
  src/pages/LoginPage.tsx
Labels: design, feat

#25 [feat] 프로필 직무 등록 (직무, 학력)
  src/App.tsx
  src/components/profile/DropDown.tsx
  src/components/profile/NextButton.tsx
  src/pages/profile/ProfileInfoPage.tsx
  src/pages/profile/ProfileJobPage.tsx
Labels: design, feat

#32 [feat] 프로필 나의 링크 등록
  src/App.tsx
  src/components/profile/InputField.tsx
  src/components/profile/InputFieldLabel.tsx
  src/components/profile/LinkInput.tsx
  src/pages/profile/ProfileLinkPage.tsx
Labels: design, feat

#36 [feat] 프로필 자기소개 등록
  src/App.tsx
  src/pages/profile/ProfileIntroPage.tsx
Labels: design, feat

#38 [feat] 프로필 데이터 등록
  src/pages/profile/ProfileImgPage.tsx
  src/pages/profile/ProfileInfoPage.tsx
  src/pages/profile/ProfileInterestPage.tsx
  src/pages/profile/ProfileIntroPage.tsx
  src/pages/profile/ProfileJobPage.tsx
  src/pages/profile/ProfileLinkPage.tsx
  src/stores/useProfileStore.ts
Labels: feat

#41 [feat] 랜딩 페이지
  package.json
  pnpm-lock.yaml
  src/App.tsx
  src/assets/chatSample.json
  src/assets/images/heroImage.svg
  src/assets/images/logo.svg
  src/assets/images/profileSample.svg
  src/assets/images/radarSample.svg
  src/assets/images/whiteradar.svg
  src/components/Landing/CTAbtn.tsx
  src/components/Landing/Desc.tsx
  src/components/Landing/FAQAccordion.tsx
  src/components/Landing/FAQSection.tsx
  src/components/Landing/LandingCard.tsx
  src/components/Landing/LandingNav.tsx
  src/components/Landing/LandingTitle.tsx
  src/components/Landing/Section2.tsx
  src/components/Landing/Section3.tsx
  src/components/Landing/Section4.tsx
  src/components/Landing/SectionMotion.tsx
  src/pages/LandingPage.tsx
  tailwind.config.ts
Labels: design, feat

#46 [fix] localStorage 제거 및 인증 기반 채팅 연동 에러 해결
  src/hooks/useChatRequestFetch.ts
  src/pages/TestPage.tsx
Labels: fix

#55 [feat] 프로필 그래픽 추가
  src/App.tsx
  src/assets/images/onContents1.svg
  src/assets/images/onContents2.svg
  src/components/profile/DropDown.tsx
  src/components/profile/Modal.tsx
  src/components/profile/ModalContent.tsx
  src/components/profile/NextButton.tsx
  src/components/profile/OnboardingContents.tsx
  src/components/profile/TopNav.tsx
  src/pages/LoginPage.tsx
  src/pages/profile/LoginPage.tsx
  src/pages/profile/ProfileImgPage.tsx
  src/pages/profile/ProfileInfoPage.tsx
  src/pages/profile/ProfileInterestPage.tsx
  src/pages/profile/ProfileIntroPage.tsx
  src/pages/profile/ProfileJobPage.tsx
  src/pages/profile/ProfileLinkPage.tsx
  src/pages/profile/layout/ProfileLayout.tsx
Labels: design, feat

#70 [feat] 채팅 장문 메세지 전송시 전체 보기 기능
  package.json
  pnpm-lock.yaml
  src/components/chatting/ChatBubble.tsx
  src/components/chatting/ChatInput.tsx
  src/components/chatting/ChatMessageItem.tsx
  src/components/chatting/ChatRoom.tsx
  src/components/chatting/FullMessageViewer.tsx
  src/pages/ChatPage.tsx
  src/pages/TestPage.tsx
  src/services/authApi.ts
Labels: design, feat
